---
title: "Análisis de Serie Multivariante"
author: "David Botin"
date: "26/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

===========================================================================================================================
===========================================================================================================================

# Cargamos las librerías necesarias

```{r,warning=FALSE,message=FALSE}
# Cargamos todos los paquetes necesarios
list.of.packages <- c("tidyr","ggplot2","readxl","forecast","lmtest","tseries","reshape2","ggpubr","car","stringr") 
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages) > 0) {
  install.packages(new.packages)
}

lapply(list.of.packages, require, character.only = T)
rm(list.of.packages, new.packages)

```

# Lectura de la Base de datos

```{r}
load("Data.RData")
```
===========================================================================================================================
===========================================================================================================================

# *Analisis Serie multivariante*

Representamos inicialmente la curva de lesiones y esquiadores

```{r}
#Selecciono la variable a representar
Serie_Skiers<-ts(Data$Skiers,start=c(1992),frequency=1)
#Ggplot
ggplot(Serie_Skiers, aes(time(Serie_Skiers), Serie_Skiers)) + geom_point()  + geom_line(color="steelblue") + xlab("Año") + ylab("Nº de esquiadores") + ggtitle("Serie Temporal esquiadores") + theme_classic()

Serie_Injuries<-ts(Data$`AllSport Injuries`,start=c(1992),frequency=1)
ggplot(Serie_Injuries, aes(time(Serie_Injuries), Serie_Injuries)) + geom_point()  + geom_line(color="steelblue") + xlab("Año") + ylab("Nº de Lesiones") + ggtitle("Serie Temporal lesiones") + theme_classic()
```


# Diferencias Sexo
```{r}
#Selecciono las columnas que interesan para el gráfico
Dat_Sexo<-data.frame(Data[c(1,8,11)])

#Creo una columna con los años
Dat_Sexo$Season<- c(1992:2019)

#Creo un data frame con el formato para poder aplicarlo al ggplot
NewDat_Sexo<-melt(Dat_Sexo,id="Season")

#Transformo los valores a ratio entre el numero total de lesiones
NewDat_Sexo$value<-NewDat_Sexo$value/rep(Data$`AllSport Injuries`,2)

ggplot(data=NewDat_Sexo, aes(x=Season, y=value, colour=variable)) + geom_line(size=1) + ggtitle("Lesiones según el sexo")

```

# Diferencias Deporte

```{r}
Dat_dep<-data.frame(Data[,c(1,4,5)])

Dat_dep$Season<- c(1992:2019)

NewDat_dep<-melt(Dat_dep,id="Season")

NewDat_dep$value<-NewDat_dep$value/rep(Data$`AllSport Injuries`,2)

ggplot(data=NewDat_dep, aes(x=Season, y=value, colour=variable)) + geom_line(size=1) + ggtitle("Lesiones según el deporte")
```

# Diferencias edades

```{r}
Variables_Ski<-colnames(Data)[c(1,13,15,17,19)]
Variables_Snow<-colnames(Data)[c(1,12,14,16,18)]

Dat_Ski<-Data[,Variables_Ski]
Dat_Snow<-Data[,Variables_Snow]

# Cambiamos los valores de la leyenda
Dat_Ski<-data.frame(Dat_Ski)
colnames(Dat_Ski)[c(2:5)]<-c("0-15","16-29","30-50",">=51")
Dat_Snow<-data.frame(Dat_Snow)
colnames(Dat_Snow)[c(2:5)]<-c("0-15","16-29","30-50",">=51")

Dat_Ski$Season<- c(1992:2019)
Dat_Snow$Season<- c(1992:2019)

NewDat_Ski<-melt(Dat_Ski,id="Season")
NewDat_Snow<-melt(Dat_Snow,id="Season")

NewDat_Ski$value<-NewDat_Ski$value/rep(Data$`AlpineSki Injuries`,4)
NewDat_Snow$value<-NewDat_Snow$value/rep(Data$`Snowboard Injuries`,4)

#Elimino los años de snow que no estan bien recolectados
Remove<-as.numeric(rownames(NewDat_Snow[NewDat_Snow$Season<2000,]))
NewDat_Snow<-NewDat_Snow[-Remove,]
                  
ggplot(data=NewDat_Ski, aes(x=Season, y=value, colour=variable)) + geom_line(size=1) + ggtitle("Lesiones de esquí según la edad")
ggplot(data=NewDat_Snow, aes(x=Season, y=value, colour=variable)) + geom_line(size=1) + ggtitle("Lesiones de snowboard según la edad")
```
# Diferencias tipos de lesiones

```{r}
#Selecciono las columnas(variables) de interés
Variables<-colnames(Data)[grep("ALL",colnames(Data),fixed=TRUE)]
Variables<-c(colnames(Data)[1],Variables)
Dat<-Data[,Variables]
Dat<-data.frame(Dat[,-11])
Dat$KneeLiga.ALL<-NULL

Dat$Season<- c(1992:2019)

NewDat<-melt(Dat,id="Season")

NewDat$value<-NewDat$value/rep(Data$`AlpineSki Injuries`,9)

ggplot(data=NewDat, aes(x=Season, y=value, colour=variable)) + geom_line(size=1) + ggtitle("Nº de lesiones según el tipo")
```


# Diferencias edades ACL

```{r}
Variables_ACL<-colnames(Data)[c(1,41,42,43,44,45,46)]
Dat_ACL<-data.frame(Data[,Variables_ACL])

Dat_ACL$Season<- c(1992:2019)

NewDat_ACL<-melt(Dat_ACL,id="Season")

NewDat_ACL$value<-NewDat_ACL$value/rep(Data$`AllSport Injuries`,4)

ggplot(data=NewDat_ACL, aes(x=Season, y=value, colour=variable)) + geom_line(size=1) + theme_classic() + ggtitle("Lesiones ACL por edades")
```
# Diferencias sexo ACL

```{r}
Dat_ACL_Sexo<-data.frame(Data[c(1,37,38)])

Dat_ACL_Sexo$Season<- c(1992:2019)

NewDat_ACL_Sexo<-melt(Dat_ACL_Sexo,id="Season")

NewDat_ACL_Sexo$value<-NewDat_ACL_Sexo$value/rep(Data$`AllSport Injuries`,2)

ggplot(data=NewDat_ACL_Sexo, aes(x=Season, y=value, colour=variable)) + geom_line(size=1) + ggtitle("Lesiones ACL según el sexo") + theme_classic()
```

# Diferencias deporte ACL

```{r}
Dat_ACL_dep<-data.frame(Data[c(1,35,36)])

Dat_ACL_dep$Season<- c(1992:2019)

NewDat_ACL_dep<-melt(Dat_ACL_dep,id="Season")

NewDat_ACL_dep$value<-NewDat_ACL_dep$value/rep(Data$`AllSport Injuries`,2)

ggplot(data=NewDat_ACL_dep, aes(x=Season, y=value, colour=variable)) + geom_line(size=1) + ggtitle("Lesiones ACL según el deporte") + theme_classic()
```
